apiVersion: v1
kind: Service
metadata:
  name: publicator
  labels:
    app: publicator
spec:
  ports:
    - port: 8080
      name: http-publicator
      #targetPort: 8080
    - port: 3474
      name: http-superstatic
  selector:
    app: publicator
    tier: fullstack
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: publicator-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publicator
  labels:
    app: publicator
spec:
  selector:
    matchLabels:
      app: publicator
      tier: fullstack
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: publicator
        tier: fullstack
    spec:
      containers:
      - image: alexivkin/publicator:1.1
        name: publicator
        imagePullPolicy: Always
        #command: ["bash", "-c", "tail -f /dev/null"]
        #args: ["-c", "tail -f /dev/null"]
        #args: ["sleep","10000"]
        env:
        - name: DEBUG
          value: publicator:*
        ports:
        - containerPort: 8080
          name: publicator
        - containerPort: 3474
          name: preview
        volumeMounts:
        - name: publicator-static
          mountPath: /publicator/superstatic/
        - name: publicator-config
          mountPath: /root/.config/configstore/publicator.json
          subPath: publicator.json # mount into subpath because otherwise the whole folder will be read-only, but firebase-tools tries to store stuff there
      volumes:
      - name: publicator-static
        persistentVolumeClaim:
          claimName: publicator-pvc
      - name: publicator-config
        secret:
          secretName: publicator
          items: # rename the stored file
          - key: config.json
            path: publicator.json
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: publicator
spec:
  hosts:
  - $INGRESS_FQDN
  gateways:
  - main-gateway
  http:
  - route:
    - destination:
        host: publicator
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: publicator-preview
spec:
  hosts:
  - v$INGRESS_FQDN
  gateways:
  - main-gateway
  http:
  - route:
    - destination:
        host: publicator
        port:
          number: 3474
